### PR TITLE
Emit event on install

### PR DESCRIPTION
**Pull request by Levike34**
Emit a Transfer event on install_contract() to register token's existence.  It would be best if some event was emitted on install.

### CODE REVIEW

**Comment by davidatwhiletrue** [comment]
@Levike34  Maybe it should be a `Mint` event?

**Comment by Levike34** [comment]
> @Levike34 Maybe it should be a `Mint` event?

@davidatwhiletrue That does make more sense.  For more context, I created this PR to address this issue: After deploying a new CEP18 contract, tokens do not appear in Casper Wallet until some event is emitted. Transfer works for sure, but I will have to check if Mint works as well.  Tokens only seem to appear if events_mode is enabled and after a Transfer event.  This commit I put allows tokens to be seen in one's wallet after calling install_contract

**Comment by davidatwhiletrue** [comment]
@Levike34 thanks for the context information. I just tried and, yes, emitting a `Mint` event during contract installation also makes the initial supply visible in the contract owner account.

**Comment by Levike34** [comment]
@davidatwhiletrue updated to Mint event

**Comment by deuszex** [comment]
Technically it is a Mint event.

**Review by deuszex — APPROVED** [review]
Reasonable

**Pull request merged**
